spring:
 application:
  name: API-GATEWAY
 config:
  import: configserver:http://localhost:8888
 cloud:
  gateway:
   routes:
    - id: CUSTOMER-SERVICE
      uri: lb://USER-SERVICE
      predicates:
       - Path=/customer/**
    - id: WORKER-SERVICE
      uri: lb://WORKER-SERVICE
      predicates:
       - Path=/worker/**
      
