server:
 port: 0

eureka:
 client:
  service-url:
   defaultZone: http://eureka1:8761/eureka

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/kaamgaar?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password: root
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
  open-in-view: false