server:
 port: 8888

spring:
 cloud:
  config:
   server:
    git:
     uri: https://github.com/divyanshu-tiwari/Shram-Sevak
     search-paths: config
     clone-on-start: true
 application:
  name: CONFIG-SERVER    

eureka:
 instance:
  prefer-ip-address: true
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka